// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVogRMj5ydURgSBGSRtD28JYgggdogBo4',
    appId: '1:1006973945702:web:3f9927621c92cfa4e0aaa7',
    messagingSenderId: '1006973945702',
    projectId: 'ninja-brew-crew-52dc5',
    authDomain: 'ninja-brew-crew-52dc5.firebaseapp.com',
    storageBucket: 'ninja-brew-crew-52dc5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-7hT3VXgrWdpDKTuu-6dopmuZHad3X3A',
    appId: '1:1006973945702:android:316509a2ce79ab60e0aaa7',
    messagingSenderId: '1006973945702',
    projectId: 'ninja-brew-crew-52dc5',
    storageBucket: 'ninja-brew-crew-52dc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx82eVMc2aLr1FDFKd2pRGgACVijcOjTU',
    appId: '1:1006973945702:ios:ee9d57fd5cb2c7b7e0aaa7',
    messagingSenderId: '1006973945702',
    projectId: 'ninja-brew-crew-52dc5',
    storageBucket: 'ninja-brew-crew-52dc5.firebasestorage.app',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx82eVMc2aLr1FDFKd2pRGgACVijcOjTU',
    appId: '1:1006973945702:ios:ee9d57fd5cb2c7b7e0aaa7',
    messagingSenderId: '1006973945702',
    projectId: 'ninja-brew-crew-52dc5',
    storageBucket: 'ninja-brew-crew-52dc5.firebasestorage.app',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVogRMj5ydURgSBGSRtD28JYgggdogBo4',
    appId: '1:1006973945702:web:1708528d243c60f1e0aaa7',
    messagingSenderId: '1006973945702',
    projectId: 'ninja-brew-crew-52dc5',
    authDomain: 'ninja-brew-crew-52dc5.firebaseapp.com',
    storageBucket: 'ninja-brew-crew-52dc5.firebasestorage.app',
  );
}
